version: '3'

services:
  scraper:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: jobs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: canaria1234
    container_name: scrapydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:alpine
    container_name: scrapyredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  query:
    build:
      context: .
      dockerfile: dockerfile.query
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app


volumes:
  postgres_data:
  redis_data: